collections_config:
  content:
    path: content
    name: Content
    icon: wysiwyg
  data_carousel:
    path: data/carousel
    name: Data Carousel
    icon: view_carousel
  data_clients:
    path: data/clients
    name: Data Clients
    icon: attachment
  data_features:
    path: data/features
    name: Data Features
    icon: data_array
  data_testimonials:
    path: data/testimonials
    name: Data Testimonials
    icon: attractions
  i18n:
    path: i18n
    name: I18n
    icon: iron
paths:
  static: static
  uploads: static/uploads
timezone: America/Los_Angeles
markdown:
  engine: commonmark
  options:
    gfm: true
    linkify: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    breaks: false
    xhtml: false
    attributes: false
    typographer: false
    treat_indentation_as_code: true
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
params: 
  input_types:
    - text
    - textarea
    - email
    - date
    - checkbox
    - radio
    - number
    - submit
  form_engines:
    - netlify
    - cloudcannon
