baseURL = 'https://sfraney.github.io/wilderness_pathfinder_connections/'
title = 'Wilderness Pathfinder Connections'
theme = 'hugo-universal-theme'
languageCode = 'en-us'
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[services]
[services.disqus]
# Enable comments by entering your Disqus shortname
# "disable the comments system by leaving the Shortname empty"
Shortname = ""
[services.googleAnalytics]
# Enable Google Analytics by entering your tracking code
# "Leave the id key empty to disable it"
id = ""

[menu]

# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/wildpathfinder.org/"
    weight     = 1

[[menu.main]]
    name       = "Our Story"
    identifier = "menu.our_story"
    url        = ""
    weight     = 2
    
[[menu.main]]
    name       = "Our Mission & Vision"
    url        = "/"
    weight     = 1
    parent     = "menu.our_story"

[[menu.main]]
    name       = "Our Advisory Council"
    identifier = "section.advisory"
    url        = "/advisory/"
    weight     = 2
    parent     = "menu.our_story"
    post       = 1
  
[[menu.main]]
    name       = "Follow our Journey"
    url        = "/blog/"
    weight     = 3
    parent     = "menu.our_story"
    post       = 1

[[menu.main]]
    name       = "Get Involved"
    identifier = "menu.get_involved"
    url        = "/"
    weight     = 3

[[menu.main]]
    name       = "Our Work"
    identifier = "section.our_work"
    url        = ""
    weight     = 1
    parent     = "menu.get_involved"
    post       = ""

[[menu.main]]
    name       = "Volunteer"
    url        = "/volunteer/"
    weight     = 4
    parent     = "menu.get_involved"
    post       = 1

[[menu.main]]
    name       = "Become a Mentor"
    url        = "/"
    weight     = 2
    parent     = "menu.get_involved"
    post       = 1
    
[[menu.main]]
    name       = "Join  Guide Network"
    url        = "/guide-network/"
    weight     = 3
    parent     = "menu.get_involved"
    post       = 1
    
[[menu.main]]
    name       = "Shop to Support"
    url        = "/section.Shop_to_Support/"
    weight     = 5
    parent     = "menu.get_involved"
    post       = 1
    
[[menu.main]]
    name       = "Events & Resources"
    identifier = "menu.resources"
    url        = "/img/template-homepage.png"
    weight     = 4

[[menu.main]]
    name       = "Private Membership Portal"
    url        = "/section.Closed_Membership_Portal/"
    weight     = 1
    parent     = "menu.resources"

[[menu.main]]
    name       = "Contact"
    identifier = ""
    url        = "/contact/"
    weight     = 5
    
[[menu.main]]
    name       = "Donate"
    url        = "/donate/"
    weight     = 6

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+12 34 567 89 01"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:info@wildpathfinder.org"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devcows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by Devcows using Hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "marsala"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Wilderness Pathfinder Connections empowers women veterans to become Rite of Passage Wilderness Guides by removing barriers to nature-based healing and leadership. Through mentorship and tradition, we cultivate a movement of women reclaiming their power, deepening their connection to the land, and guiding others in transformation.</p>"
    copyright = "Copyright (c) 2025, Wilderness Pathfinder Connections; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "wilderness pathfinder connections"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>TBD</strong>
        <br>info@wildpathfinder.org
        <br>Portland, Oregon
        <br><strong>United States</strong>
        Wilderness Pathfinder Connections is a 501(c)(3) nonprofit. Your donation is tax-deductible.
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us at info@wildpathfinder.org</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:info@wildpathfinder.org" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 4 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/Four/Pillars'.
    # For more information take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Why We Do This"
    subtitle = "A return to nature is a return to ourselves. By creating space for women veterans to heal, reconnect, and lead, we ensure that ancestral wisdom and personal resilience thrive."

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Join Us in the Journey"
    subtitle = "Be part of a movement that uplifts women veterans through nature-based healing and leadership. Whether through training, support, or funding, your involvement makes a difference."
    link_url = "#"
    link_text = "Get Involved | Donate"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Vision"
    subtitle = "Wilderness Pathfinder Connections envisions a world where women veterans are recognized as leaders in nature-based healing and self-generated ceremony. Through education, resources, and a strong web of guides and guides-in-training, we cultivate long-term change to cultivate cultural and community renewal. We ensure that diverse traditions are honored, knowledge is shared with integrity, and future generations have access to these transformative practices. By fostering personal growth, collective healing, and new pathways of renewal, we create lasting change for individuals and communities alike."

[params.recent_posts]
    enable = true
    title = "Latest Updates"
    subtitle = "Upcoming programs, events, and milestones."
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
